spring.application.name=votre-nom-projet
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com/postgres?user=postgres.xdzpatvesyfupvnkqfai&password=moadforgammal123.
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.compression.enabled=false
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=200MB
spring.jpa.open-in-view=false

server.address=0.0.0.0
server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true